### ISSUE TITLE
design and building of Other NeuWidgets

### ISSUE THREAD

**Issue by AirborneEagle** [mcaubrey/clay_containers#1]
I like this package. :)
Best flutter neumorphic package so far 👍 

Do you have plans for buttons, or any other widgets?
if so, do you have plans for how they will be implemented? 
I would be happy to help if I am able.

Also, it would be really cool if we could somehow tie into Flutter ThemeData, or create a NeuThemeData or something.  
I am a fan.

**Comment by MichaelCharles** [comment]
Hey sorry for the delay in response. Life caught up with me all of a sudden.

I'm sure you've moved on by now, but either way I think that I want to keep `clay_containers` a project that provides primitive widgets by which you can create more complicated widgets.

Like, instead of expanding `clay_containers` to have a `ClayButton` or a `ClayInput`, I'd rather make the existing primitives easier to use in creating things like buttons or inputs, if that makes sense.

**Comment by AirborneEagle** [comment]
Yeah, I think i follow you 👍  I'll close this off then
